import { OnboardingApplication } from '../types/onboarding.types';

export const INITIAL_APPLICATIONS: OnboardingApplication[] = [
  {
    id: 'APP-2026-891',
    companyName: 'Nova Robotics & Aerospace AI',
    applicantName: 'Dr. Sarah Vance',
    companyType: 'Private Limited Company',
    industry: 'Robotics & AI',
    businessCategory: 'DeepTech Automation',
    submissionDate: '2026-03-01T09:30:00Z',
    status: 'APPROVED',
    lastUpdated: '2026-03-04T14:20:00Z',
    logoUrl: '',
    companyInfo: {
      description: 'Pioneering autonomous robotic manipulators and spatial computing firmware for aerospace manufacturing lines.',
      foundedYear: 2023,
      companySize: '51-200 Employees',
      website: 'https://novasystems.io',
      businessEmail: 'contact@novasystems.io',
      businessPhone: '+91 80 4123 9900',
      headquarters: 'Bengaluru, India',
      locations: ['Bengaluru, India', 'San Francisco, USA', 'Munich, Germany'],
    },
    businessInfo: {
      businessModel: 'B2B Enterprise Hardware + SaaS Telemetry',
      products: ['NovaCore Spatial OS', 'NovaArm Apex-7', 'AeroGrip End-Effector'],
      services: ['Custom Cleanroom Integration', 'Robotic Fleet Telemetry SLA'],
      technologies: ['ROS2', 'Rust', 'TensorFlow', 'CUDA', 'WebRTC', 'RTOS'],
      targetMarket: 'Aerospace Prime Contractors & Defence Systems',
      businessDescription: 'We build certified industrial robotic arms capable of sub-millimeter precision welding, carbon-fiber layup, and satellite structural assembly with AI-assisted defect inspection.',
    },
    legalInfo: {
      legalName: 'Nova Robotics & Aerospace Systems Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U72900KA2023PTC174829',
      incorporationDate: '2023-04-12',
      registeredAddress: 'Plot 42, Electronic City Phase 1, Hosur Road',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      postalCode: '560100',
    },
    gstInfo: {
      gstNumber: '29AABCN1234F1Z5',
      cinNumber: 'U72900KA2023PTC174829',
      panNumber: 'AABCN1234F',
      isVerified: true,
    },
    representative: {
      fullName: 'Dr. Sarah Vance',
      designation: 'Co-Founder & Chief Executive Officer',
      email: 'sarah.vance@novasystems.io',
      phone: '+91 91234 56789',
      relationship: 'Authorized Director & Majority Shareholder',
    },
    documents: [
      {
        id: 'DOC-101',
        name: 'Certificate_of_Incorporation_MCA.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-01T09:35:00Z',
        status: 'VERIFIED',
        fileSize: 2450000,
        comment: 'Verified with MCA Registry portal.',
      },
      {
        id: 'DOC-102',
        name: 'GST_Registration_Certificate_Form_REG06.pdf',
        type: 'GST Certificate',
        uploadedAt: '2026-03-01T09:36:00Z',
        status: 'VERIFIED',
        fileSize: 1850000,
        comment: 'GST active status confirmed.',
      },
      {
        id: 'DOC-103',
        name: 'Board_Resolution_Representative_Authority.pdf',
        type: 'Legal Authorization',
        uploadedAt: '2026-03-01T09:40:00Z',
        status: 'VERIFIED',
        fileSize: 980000,
        comment: 'Signed by all active directors.',
      },
    ],
    internalNotes: [
      {
        id: 'NOTE-01',
        author: 'Vikramaditya Roy',
        authorRole: 'Principal Admin',
        note: 'High-quality deeptech startup with institutional backing from Sequoia and Blume. MCA filings and GST checks fully validated.',
        timestamp: '2026-03-02T11:15:00Z',
      },
      {
        id: 'NOTE-02',
        author: 'Vikramaditya Roy',
        authorRole: 'Principal Admin',
        note: 'Approved application and provisioned Company Owner dashboard clearance.',
        timestamp: '2026-03-04T14:20:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-01',
        status: 'SUBMITTED',
        title: 'Onboarding Application Submitted',
        description: 'Application received with 3 supporting legal documents.',
        timestamp: '2026-03-01T09:30:00Z',
        actor: 'Dr. Sarah Vance',
      },
      {
        id: 'TL-02',
        status: 'UNDER_REVIEW',
        title: 'Assigned for Administrative Review',
        description: 'Document and GST verification assigned to compliance team.',
        timestamp: '2026-03-02T10:00:00Z',
        actor: 'System Admin',
      },
      {
        id: 'TL-03',
        status: 'APPROVED',
        title: 'Application Approved',
        description: 'Company verified successfully. Company Owner portal access granted and listing published.',
        timestamp: '2026-03-04T14:20:00Z',
        actor: 'Vikramaditya Roy (Admin)',
      },
    ],
  },
  {
    id: 'APP-2026-892',
    companyName: 'Aether Cloud HyperScale',
    applicantName: 'David Chen',
    companyType: 'Public Limited Company',
    industry: 'Cloud Infrastructure',
    businessCategory: 'Enterprise Infrastructure',
    submissionDate: '2026-03-05T11:00:00Z',
    status: 'UNDER_REVIEW',
    lastUpdated: '2026-03-06T16:45:00Z',
    companyInfo: {
      description: 'Distributed bare-metal GPU computing cloud for foundation model training and high-throughput inference.',
      foundedYear: 2021,
      companySize: '201-500 Employees',
      website: 'https://aethercloud.tech',
      businessEmail: 'enterprise@aethercloud.tech',
      businessPhone: '+91 22 6789 0123',
      headquarters: 'Mumbai, India',
      locations: ['Mumbai, India', 'Hyderabad, India', 'Singapore'],
    },
    businessInfo: {
      businessModel: 'Infrastructure as a Service (IaaS)',
      products: ['AetherCompute H100 Clusters', 'HyperMesh Storage'],
      services: ['Managed Kubernetes for AI', 'Direct Optical Connect'],
      technologies: ['Kubernetes', 'Ceph', 'NVIDIA NeMo', 'InfiniBand', 'BGP'],
      targetMarket: 'AI Labs, Fintech Enterprises, Data Research Centers',
      businessDescription: 'Providing hyperscale GPU compute nodes across tier-4 data centers with renewable energy certification.',
    },
    legalInfo: {
      legalName: 'Aether Cloud Infrastructure Technologies India Limited',
      registrationType: 'Public Limited',
      registrationNumber: 'L72200MH2021PLC354890',
      incorporationDate: '2021-08-19',
      registeredAddress: 'Tower 3, Bandra-Kurla Complex, Bandra East',
      country: 'India',
      state: 'Maharashtra',
      city: 'Mumbai',
      postalCode: '400051',
    },
    gstInfo: {
      gstNumber: '27AAACA5678B1Z2',
      cinNumber: 'L72200MH2021PLC354890',
      panNumber: 'AAACA5678B',
      isVerified: true,
    },
    representative: {
      fullName: 'David Chen',
      designation: 'Managing Director & VP APAC',
      email: 'david.chen@aethercloud.tech',
      phone: '+91 98201 23456',
      relationship: 'Authorized Signatory',
    },
    documents: [
      {
        id: 'DOC-201',
        name: 'MCA_Public_Limited_Incorporation.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-05T11:05:00Z',
        status: 'VERIFIED',
        fileSize: 4200000,
        comment: 'Valid CIN and active ROC record.',
      },
      {
        id: 'DOC-202',
        name: 'DataCenter_Tier4_Certification.pdf',
        type: 'Compliance Certificate',
        uploadedAt: '2026-03-05T11:10:00Z',
        status: 'PENDING',
        fileSize: 3100000,
        comment: 'Pending technical audit cross-check.',
      },
    ],
    internalNotes: [
      {
        id: 'NOTE-03',
        author: 'Vikramaditya Roy',
        authorRole: 'Admin',
        note: 'Checking tier-4 compliance with Uptime Institute records. Public filings look solid.',
        timestamp: '2026-03-06T10:00:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-11',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'Hyperscale infrastructure application received.',
        timestamp: '2026-03-05T11:00:00Z',
        actor: 'David Chen',
      },
      {
        id: 'TL-12',
        status: 'UNDER_REVIEW',
        title: 'Admin Review Commenced',
        description: 'Verifying data center uptime certificates and telecom leased-line agreements.',
        timestamp: '2026-03-06T09:30:00Z',
        actor: 'Admin Reviewer',
      },
    ],
  },
  {
    id: 'APP-2026-893',
    companyName: 'Quantum FinTech Labs',
    applicantName: 'Pooja Verma',
    companyType: 'Private Limited Company',
    industry: 'FinTech & DeFi',
    businessCategory: 'Payment Infrastructure',
    submissionDate: '2026-03-07T14:15:00Z',
    status: 'MORE_INFORMATION_REQUIRED',
    lastUpdated: '2026-03-08T11:00:00Z',
    companyInfo: {
      description: 'Next-generation cross-border settlement API and multi-currency treasury engine.',
      foundedYear: 2024,
      companySize: '11-50 Employees',
      website: 'https://quantumfintech.io',
      businessEmail: 'info@quantumfintech.io',
      businessPhone: '+91 11 4567 8901',
      headquarters: 'New Delhi, India',
      locations: ['New Delhi, India', 'London, UK'],
    },
    businessInfo: {
      businessModel: 'B2B Transaction Fee & API Subscription',
      products: ['QuantumRail API', 'SmartTreasury Dashboard'],
      services: ['Cross-border fx liquidity', 'Automated compliance routing'],
      technologies: ['Node.js', 'Go', 'PostgreSQL', 'Redis', 'ISO 20022'],
      targetMarket: 'Importers, Exporters, and Digital Neo-Banks',
      businessDescription: 'Providing compliant real-time settlements under RBI regulatory sandbox guidelines.',
    },
    legalInfo: {
      legalName: 'Quantum FinTech Labs Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U65999DL2024PTC412389',
      incorporationDate: '2024-01-18',
      registeredAddress: 'Level 5, Connaught Place Outer Circle',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      postalCode: '110001',
    },
    gstInfo: {
      gstNumber: '07AAACQ9876E1Z4',
      cinNumber: 'U65999DL2024PTC412389',
      panNumber: 'AAACQ9876E',
      isVerified: false,
    },
    representative: {
      fullName: 'Pooja Verma',
      designation: 'Chief Compliance Officer',
      email: 'pooja.verma@quantumfintech.io',
      phone: '+91 98111 22334',
      relationship: 'Authorized Officer',
    },
    documents: [
      {
        id: 'DOC-301',
        name: 'COI_Quantum_Fintech.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-07T14:20:00Z',
        status: 'VERIFIED',
        fileSize: 1200000,
      },
      {
        id: 'DOC-302',
        name: 'RBI_Sandbox_Authorization_Letter.pdf',
        type: 'Regulatory License',
        uploadedAt: '2026-03-07T14:25:00Z',
        status: 'ACTION_REQUIRED',
        fileSize: 850000,
        comment: 'Document was missing official annexure B and signature of authorized RBI nodal officer.',
      },
    ],
    internalNotes: [
      {
        id: 'NOTE-04',
        author: 'Vikramaditya Roy',
        authorRole: 'Admin',
        note: 'Requested updated RBI Sandbox approval letter with complete Annexure B.',
        timestamp: '2026-03-08T11:00:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-21',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'Fintech onboarding application submitted.',
        timestamp: '2026-03-07T14:15:00Z',
        actor: 'Pooja Verma',
      },
      {
        id: 'TL-22',
        status: 'UNDER_REVIEW',
        title: 'Compliance Check Commenced',
        description: 'Regulatory license verification started.',
        timestamp: '2026-03-08T09:00:00Z',
        actor: 'Admin Reviewer',
      },
      {
        id: 'TL-23',
        status: 'MORE_INFORMATION_REQUIRED',
        title: 'Additional Documentation Requested',
        description: 'Admin requested updated RBI regulatory license copy with Annexure B.',
        timestamp: '2026-03-08T11:00:00Z',
        actor: 'Vikramaditya Roy (Admin)',
        remarks: 'Please re-upload RBI regulatory sandbox letter with all formal annexures and authorized signature.',
      },
    ],
  },
  {
    id: 'APP-2026-894',
    companyName: 'BioVance Therapeutics',
    applicantName: 'Dr. Marcus Sterling',
    companyType: 'Limited Liability Partnership',
    industry: 'Biotechnology',
    businessCategory: 'Genomics & Biopharma',
    submissionDate: '2026-03-08T16:00:00Z',
    status: 'SUBMITTED',
    lastUpdated: '2026-03-08T16:00:00Z',
    companyInfo: {
      description: 'AI-driven drug discovery for targeted oncology and rare autoimmune therapeutics.',
      foundedYear: 2022,
      companySize: '11-50 Employees',
      website: 'https://biovancetx.com',
      businessEmail: 'contact@biovancetx.com',
      businessPhone: '+91 40 2345 6789',
      headquarters: 'Hyderabad, India',
      locations: ['Hyderabad Genome Valley, India', 'Cambridge, USA'],
    },
    businessInfo: {
      businessModel: 'IP Licensing & Clinical Co-Development',
      products: ['OncoTarget AI Platform', 'BV-402 Molecule Candidate'],
      services: ['Targeted Molecular Screening', 'High-throughput Assay'],
      technologies: ['PyTorch', 'AlphaFold2', 'Cryo-EM Pipeline', 'AWS Batch'],
      targetMarket: 'Global Pharmaceutical Enterprises & Research Hospitals',
      businessDescription: 'Developing synthetic biology small-molecules with preclinical computational validation.',
    },
    legalInfo: {
      legalName: 'BioVance Therapeutics LLP',
      registrationType: 'LLP',
      registrationNumber: 'AAY-9012',
      incorporationDate: '2022-11-05',
      registeredAddress: 'Building 4B, Genome Valley, Shamirpet',
      country: 'India',
      state: 'Telangana',
      city: 'Hyderabad',
      postalCode: '500078',
    },
    gstInfo: {
      gstNumber: '36AAHFB1234M1Z8',
      cinNumber: 'LLP-AAY-9012',
      panNumber: 'AAHFB1234M',
      isVerified: false,
    },
    representative: {
      fullName: 'Dr. Marcus Sterling',
      designation: 'Managing Partner & Head of Research',
      email: 'm.sterling@biovancetx.com',
      phone: '+91 94401 98765',
      relationship: 'Designated Partner',
    },
    documents: [
      {
        id: 'DOC-401',
        name: 'LLP_Agreement_and_Registration.pdf',
        type: 'LLP Agreement',
        uploadedAt: '2026-03-08T16:05:00Z',
        status: 'PENDING',
        fileSize: 3800000,
      },
    ],
    internalNotes: [],
    timeline: [
      {
        id: 'TL-31',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'New biotech LLP registration received. Awaiting queue assignment.',
        timestamp: '2026-03-08T16:00:00Z',
        actor: 'Dr. Marcus Sterling',
      },
    ],
  },
  {
    id: 'APP-2026-895',
    companyName: 'OmniLogix Autonomous Freight',
    applicantName: 'Aarav Sharma',
    companyType: 'Private Limited Company',
    industry: 'Logistics & Supply Chain',
    businessCategory: 'Autonomous Transport',
    submissionDate: '2026-02-20T10:00:00Z',
    status: 'REJECTED',
    lastUpdated: '2026-02-23T15:30:00Z',
    companyInfo: {
      description: 'Long-haul autonomous trucking telematics and route optimization.',
      foundedYear: 2024,
      companySize: '1-10 Employees',
      website: 'https://omnilogix.example.com',
      businessEmail: 'info@omnilogix.example.com',
      businessPhone: '+91 44 2828 1111',
      headquarters: 'Chennai, India',
      locations: ['Chennai, India'],
    },
    businessInfo: {
      businessModel: 'Freight Marketplace',
      products: ['OmniRoute'],
      services: ['Brokerage'],
      technologies: ['React', 'Node'],
      targetMarket: 'Fleet operators',
      businessDescription: 'Freight aggregation app.',
    },
    legalInfo: {
      legalName: 'OmniLogix Logistics Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U60200TN2024PTC999999',
      incorporationDate: '2024-02-01',
      registeredAddress: 'Anna Nagar, Chennai',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      postalCode: '600040',
    },
    gstInfo: {
      gstNumber: '33AAACT9999K1Z0',
      cinNumber: 'U60200TN2024PTC999999',
      panNumber: 'AAACT9999K',
      isVerified: false,
    },
    representative: {
      fullName: 'Aarav Sharma',
      designation: 'Director',
      email: 'aarav@omnilogix.example.com',
      phone: '+91 98400 11223',
      relationship: 'Director',
    },
    documents: [],
    internalNotes: [
      {
        id: 'NOTE-05',
        author: 'Vikramaditya Roy',
        authorRole: 'Admin',
        note: 'Applicant provided forged GST registration number and invalid CIN format. Rejected during KYC screening.',
        timestamp: '2026-02-23T15:30:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-41',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'Application received.',
        timestamp: '2026-02-20T10:00:00Z',
        actor: 'Aarav Sharma',
      },
      {
        id: 'TL-42',
        status: 'REJECTED',
        title: 'Application Rejected',
        description: 'Entity verification failed KYC and GST authenticity checks.',
        timestamp: '2026-02-23T15:30:00Z',
        actor: 'Vikramaditya Roy (Admin)',
        remarks: 'GST and MCA registration numbers could not be validated on official government registries.',
      },
    ],
  },
  {
    id: 'APP-2026-896',
    companyName: 'Kavach Cyber Defense Labs',
    applicantName: 'Vikramjit Sahni',
    companyType: 'Private Limited Company',
    industry: 'Cybersecurity',
    businessCategory: 'Threat Intelligence & Zero-Trust',
    submissionDate: '2026-03-10T11:20:00Z',
    status: 'DRAFT',
    lastUpdated: '2026-03-10T11:20:00Z',
    companyInfo: {
      description: 'Quantum-safe endpoint telemetry and sovereign data defense infrastructure for Indian critical assets.',
      foundedYear: 2024,
      companySize: '11-50 Employees',
      website: 'https://kavachcyber.in',
      businessEmail: 'contact@kavachcyber.in',
      businessPhone: '+91 11 2987 6543',
      headquarters: 'New Delhi, India',
      locations: ['New Delhi, India'],
    },
    businessInfo: {
      businessModel: 'Enterprise Annual License & Sovereign SOC',
      products: ['KavachShield XDR', 'ZeroTrust Sentinel'],
      services: ['Red Team Assessment', 'Incident Response SLA'],
      technologies: ['eBPF', 'Rust', 'WASM', 'Kafka', 'ClickHouse'],
      targetMarket: 'Defence PSUs, Banking Nodes, Critical Infrastructure',
      businessDescription: 'Building CERT-In compliant defensive telemetry fabrics.',
    },
    legalInfo: {
      legalName: 'Kavach Cyber Defense Technologies Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U72900DL2024PTC429810',
      incorporationDate: '2024-03-01',
      registeredAddress: 'Tech Spire, Nehru Place',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      postalCode: '110019',
    },
    gstInfo: {
      gstNumber: '07AAACK5432P1Z1',
      cinNumber: 'U72900DL2024PTC429810',
      panNumber: 'AAACK5432P',
      isVerified: false,
    },
    representative: {
      fullName: 'Vikramjit Sahni',
      designation: 'Managing Director & Founder',
      email: 'v.sahni@kavachcyber.in',
      phone: '+91 98100 87654',
      relationship: 'Authorized Signatory',
    },
    documents: [
      {
        id: 'DOC-501',
        name: 'Incorporation_COI_Draft.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-10T11:25:00Z',
        status: 'PENDING',
        fileSize: 1800000,
      },
    ],
    internalNotes: [],
    timeline: [
      {
        id: 'TL-51',
        status: 'DRAFT',
        title: 'Verification Packet Initiated',
        description: 'Verification packet created by company representative. Submission pending statutory signoff.',
        timestamp: '2026-03-10T11:20:00Z',
        actor: 'Vikramjit Sahni',
      },
    ],
  },
  {
    id: 'APP-2026-897',
    companyName: 'Solaris CleanGrid Energy',
    applicantName: 'Meera Patel',
    companyType: 'Private Limited Company',
    industry: 'CleanTech & Energy',
    businessCategory: 'Renewable Storage & Grid AI',
    submissionDate: '2026-03-09T14:40:00Z',
    status: 'MORE_INFORMATION_REQUIRED',
    lastUpdated: '2026-03-10T09:15:00Z',
    companyInfo: {
      description: 'Distributed Battery Energy Storage Systems (BESS) and AI-guided dynamic power dispatch algorithms.',
      foundedYear: 2022,
      companySize: '51-200 Employees',
      website: 'https://solariscleangrid.com',
      businessEmail: 'info@solariscleangrid.com',
      businessPhone: '+91 79 2654 3210',
      headquarters: 'Ahmedabad, India',
      locations: ['Ahmedabad, Gujarat', 'Jaipur, Rajasthan'],
    },
    businessInfo: {
      businessModel: 'Clean Energy EPC + Performance Telemetry',
      products: ['GridSync Inverter Core', 'Solaris Lithium-LFP Battery Stack'],
      services: ['Grid Stabilization SLA', 'Battery Degradation Forecasting'],
      technologies: ['MATLAB', 'C++', 'Python', 'Modbus', 'SCADA'],
      targetMarket: 'Discoms, Solar Park Developers, Commercial Industrial Microgrids',
      businessDescription: 'Utility-scale energy storage solutions with multi-hour duration.',
    },
    legalInfo: {
      legalName: 'Solaris CleanGrid Energy Systems Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U40106GJ2022PTC132981',
      incorporationDate: '2022-07-14',
      registeredAddress: 'Solaris Towers, SG Highway, Bodakdev',
      country: 'India',
      state: 'Gujarat',
      city: 'Ahmedabad',
      postalCode: '380054',
    },
    gstInfo: {
      gstNumber: '24AAACS9876Q1Z3',
      cinNumber: 'U40106GJ2022PTC132981',
      panNumber: 'AAACS9876Q',
      isVerified: true,
    },
    representative: {
      fullName: 'Meera Patel',
      designation: 'Director & Chief Technical Officer',
      email: 'meera.p@solariscleangrid.com',
      phone: '+91 98250 12345',
      relationship: 'Authorized Director',
    },
    documents: [
      {
        id: 'DOC-601',
        name: 'MCA_COI_Solaris.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-09T14:45:00Z',
        status: 'VERIFIED',
        fileSize: 2100000,
      },
      {
        id: 'DOC-602',
        name: 'CEA_Grid_Interconnection_Approval.pdf',
        type: 'Grid Compliance Certificate',
        uploadedAt: '2026-03-09T14:50:00Z',
        status: 'ACTION_REQUIRED',
        fileSize: 1450000,
        comment: 'Missing official state load dispatch center (SLDC) telemetry clearance stamp.',
      },
    ],
    internalNotes: [
      {
        id: 'NOTE-06',
        author: 'Vikramaditya Roy',
        authorRole: 'Admin',
        note: 'Requested updated SLDC compliance annexure.',
        timestamp: '2026-03-10T09:15:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-61',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'CleanTech energy verification packet submitted.',
        timestamp: '2026-03-09T14:40:00Z',
        actor: 'Meera Patel',
      },
      {
        id: 'TL-62',
        status: 'MORE_INFORMATION_REQUIRED',
        title: 'SLDC Telemetry Certificate Required',
        description: 'Admin requested SLDC stamp on CEA Grid Interconnection document.',
        timestamp: '2026-03-10T09:15:00Z',
        actor: 'Vikramaditya Roy (Admin)',
        remarks: 'Please upload SLDC stamped telemetry clearance certificate to complete grid compliance audit.',
      },
    ],
  },
  {
    id: 'APP-2026-898',
    companyName: 'Zenith Semiconductor Labs',
    applicantName: 'Rajesh Nair',
    companyType: 'Private Limited Company',
    industry: 'Semiconductors & Hardware',
    businessCategory: 'Fabless ASIC & RISC-V Silicon',
    submissionDate: '2026-03-06T15:30:00Z',
    status: 'UNDER_REVIEW',
    lastUpdated: '2026-03-07T12:00:00Z',
    companyInfo: {
      description: 'Fabless semiconductor design house specializing in automotive-grade RISC-V edge AI microcontrollers.',
      foundedYear: 2023,
      companySize: '11-50 Employees',
      website: 'https://zenithsemi.io',
      businessEmail: 'contact@zenithsemi.io',
      businessPhone: '+91 120 456 7890',
      headquarters: 'Noida, India',
      locations: ['Noida Sector 62, Uttar Pradesh', 'Bengaluru, Karnataka'],
    },
    businessInfo: {
      businessModel: 'Silicon IP Licensing & ASIC Production',
      products: ['Zenith-V Edge SoC', 'NeuralAccel NPU Core'],
      services: ['Custom Silicon Layout', 'Tapeout Verification'],
      technologies: ['Verilog', 'Chisel', 'OpenROAD', 'Cadence', 'TSMC 28nm'],
      targetMarket: 'EV Tier-1 Suppliers, Industrial IoT, Aerospace Telemetry',
      businessDescription: 'Developing sovereign RISC-V compute processors with hardware security enclave.',
    },
    legalInfo: {
      legalName: 'Zenith Semiconductor Technologies Private Limited',
      registrationType: 'Private Limited',
      registrationNumber: 'U72900UP2023PTC189201',
      incorporationDate: '2023-09-15',
      registeredAddress: 'Tower B, Logix Cyber Park, Sector 62',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Noida',
      postalCode: '201309',
    },
    gstInfo: {
      gstNumber: '09AAACZ1234R1Z7',
      cinNumber: 'U72900UP2023PTC189201',
      panNumber: 'AAACZ1234R',
      isVerified: true,
    },
    representative: {
      fullName: 'Rajesh Nair',
      designation: 'Founder & Chief Silicon Architect',
      email: 'r.nair@zenithsemi.io',
      phone: '+91 99100 23456',
      relationship: 'Authorized Director',
    },
    documents: [
      {
        id: 'DOC-701',
        name: 'MCA_COI_Zenith.pdf',
        type: 'Incorporation Document',
        uploadedAt: '2026-03-06T15:35:00Z',
        status: 'VERIFIED',
        fileSize: 2600000,
      },
      {
        id: 'DOC-702',
        name: 'India_Semiconductor_Mission_ISM_Accreditation.pdf',
        type: 'Statutory Accreditation',
        uploadedAt: '2026-03-06T15:40:00Z',
        status: 'VERIFIED',
        fileSize: 3100000,
      },
    ],
    internalNotes: [
      {
        id: 'NOTE-07',
        author: 'Vikramaditya Roy',
        authorRole: 'Admin',
        note: 'ISM accreditation verified with MeitY records. Final compliance signoff in progress.',
        timestamp: '2026-03-07T12:00:00Z',
      },
    ],
    timeline: [
      {
        id: 'TL-71',
        status: 'SUBMITTED',
        title: 'Application Submitted',
        description: 'Semiconductor design verification packet submitted.',
        timestamp: '2026-03-06T15:30:00Z',
        actor: 'Rajesh Nair',
      },
      {
        id: 'TL-72',
        status: 'UNDER_REVIEW',
        title: 'Technical Review In Progress',
        description: 'Verifying ISM subsidy eligibility and IP ownership records.',
        timestamp: '2026-03-07T10:00:00Z',
        actor: 'Admin Reviewer',
      },
    ],
  },
];
