export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    APPLICATIONS: '/admin/applications',
    APPLICATION_DETAILS: (id: string = ':id') => `/admin/applications/${id}`,
    SERVICE_DETAILS: (id: string = ':id') => `/admin/services/${id}`,
    SERVICE_CREATE: '/admin/services/create',
    COMPANIES: '/admin/companies',
    COMPANY_ONBOARD: '/admin/companies/onboard',
    COMPANY_DETAILS: (id: string = ':id') => `/admin/companies/${id}`,
    COMPANY_EDIT: (id: string = ':id') => `/admin/companies/${id}/edit`,
    LISTINGS: '/admin/listings',
    LISTING_DETAILS: (id: string = ':id') => `/admin/listings/${id}`,
    SERVICE_PROVIDERS: '/admin/service-providers',
    SERVICE_PROVIDER_DETAILS: (id: string = ':id') => `/admin/service-providers/${id}`,
    USERS: '/admin/users',
    USER_CREATE: '/admin/users/create',
    USER_DETAILS: (id: string = ':id') => `/admin/users/${id}`,
    DOCUMENTS: '/admin/documents',
    DOCUMENT_DETAILS: (id: string = ':id') => `/admin/documents/${id}`,
    NOTIFICATIONS: '/admin/notifications',
    NOTIFICATION_CREATE: '/admin/notifications/create',
    NOTIFICATION_DETAILS: (id: string = ':id') => `/admin/notifications/${id}`,
    NOTIFICATION_TEMPLATES: '/admin/notification-templates',
    TEMPLATE_CREATE: '/admin/notification-templates/create',
    TEMPLATE_EDIT: (id: string = ':id') => `/admin/notification-templates/${id}/edit`,
    REPORTS: '/admin/reports',
    AUDIT_LOGS: '/admin/audit-logs',
    AUDIT_LOG_DETAILS: (id: string = ':id') => `/admin/audit-logs/${id}`,
    CMS: '/admin/cms',
    SETTINGS: '/admin/settings',
    ACCOUNT: '/admin/account',
  },
  COMPANY_OWNER: {
    ROOT: '/company',
    DASHBOARD: '/company/dashboard',
    MY_COMPANY: '/company/my-company',
    MY_COMPANY_EDIT: '/company/my-company/edit',
    MY_SERVICES: '/company/my-services',
    SERVICE_CREATE: '/company/my-services/create',
    SERVICE_DETAILS: (id: string = ':id') => `/company/my-services/${id}`,
    MY_LISTING: '/company/my-listing',
    MY_LISTING_EDIT: '/company/my-listing/edit',
    DOCUMENTS: '/company/documents',
    DOCUMENT_DETAILS: (id: string = ':id') => `/company/documents/${id}`,
    CONNECTIONS: '/company/connections',
    DISCOVER_COMPANIES: '/company/discover',
    DISCOVER_COMPANY_DETAILS: (id: string = ':id') => `/company/discover/${id}`,
    NOTIFICATIONS: '/company/notifications',
    NOTIFICATION_DETAILS: (id: string = ':id') => `/company/notifications/${id}`,
    ACCOUNT: '/company/account',
    SETTINGS: '/company/settings',
    ONBOARDING_HISTORY: '/company/onboarding-history',
    ANALYTICS: '/company/analytics',
  },
  COMMON: {
    UNAUTHORIZED: '/unauthorized',
    NOT_FOUND: '/not-found',
  }
} as const;
